version: '3.9'

services:
  nest-template-api:
    container_name: nest-template-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    environment:
      - BASE_URL=${BASE_URL}
      - TOKEN_DEVELOPMENT=${TOKEN_DEVELOPMENT}
      - ALLOWED_URLS=${ALLOWED_URLS}
      - MONGO_DATABASE_URL=${MONGO_DATABASE_URL}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - PORT=${PORT}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - mongo-template
      - postgres-template
    networks:
      - nest-template-network

  pgadmin-template:
    container_name: pgadmin-template
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "4000:80"
    networks:
      - nest-template-network
    depends_on:
      - postgres-template
  postgres-template:
      container_name: postgres-template
      image: postgres:15
      command: ["postgres", "-p", "${POSTGRES_PORT}", "-c", "max_connections=1000"]
      restart: always
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - nest-template-network

  mongo-template:
    image: mongo:6.0
    container_name: mongo-template
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-template-network

  redis-template:
    image: redis:latest
    container_name: redis-template
    command: >
      redis-server --port ${REDIS_PORT} --appendonly yes --save ""
    volumes:
      - evolution_redis:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - nest-template-network
  evolution-api-template:
    container_name: evolution-api-template
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - nest-template-network
    depends_on:
      - postgres-template
      - redis-template
      
volumes:
  evolution_instances:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  mongo-data:

networks:
  nest-template-network:
    name: nest-template-network
    driver: bridge